name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.TOKEN }}
        run: |
          echo "$SUPER_SECRET"

      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: 'Message that will be displayed on users first issue'
          pr-message: 'Message that will be displayed on users first pull request'
